### ISSUE TITLE
include a renderNode function in PasteLinkify plugin?

### ISSUE THREAD

**Issue by davidchang** [ianstormtaylor/slate-plugins#19]
What do you think about including a basic renderNode function for the PasteLinkify plugin? something like this:

```
renderNode = props => {
    const { node, attributes, children } = props;
    switch (node.type) {
      case 'link':
        return (
          <a {...attributes} href={node.data.get('url')}>
            {children}
          </a>
        );
      default:
        return null;
    }
  };
```

may not be a one size fits all, but i think it's generally sufficient

**Comment by ianstormtaylor** [comment]
Hey @davidchang, good question. In general I think plugins should tend towards being mostly about **behavior**, and usually they should avoid **rendering** and **schema** decisions. This ends up making them flexible enough that they can be used across a range of use cases. 

In this case, it's a deliberate decision to decouple the idea of "creating a link" from rendering it, since people could choose to do different sorts of things.
