### ISSUE TITLE
AutoSave plugin

### ISSUE THREAD

**Issue by sahalsajjad** [ianstormtaylor/slate-plugins#20]
#### Do you want to request a *feature* or report a *bug*?
Feature

#### What's the expected behavior?

Any plans to make an auto save plugin? If not, could you help me with how to implement one. I need to autosave every time there is a 3 sec delay after last `onChange`. Currently I have tried doing this functionality with `lodash.throttle`, but I am not sure if that is the correct way of implementing autosave.

There seems to be a plugin out there -> https://github.com/komcal/slate-auto-save , but since it is not officially supported, I don't know how safe it is to use that.
Thanks in advance :slightly_smiling_face:

**Comment by ianstormtaylor** [comment]
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!
